let dbPromise=null;
const norm=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const valid=n=>typeof n==='number'&&Number.isFinite(n);
const round=n=>Math.round(n*100)/100;
export async function loadHistoricalDB(){if(!dbPromise)dbPromise=fetch('/data/historical-db.json',{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error('Base histórica precargada no disponible.');return r.json();});return dbPromise;}
const compAliases={'premier-league':'PL','championship':'ELC','bundesliga':'BL1','bundesliga-2':'BL2','laliga':'PD','ligue-1':'FL1','serie-a':'SA','primeira-liga':'PPL'};
export async function getLeagueTeams(leagueId){const db=await loadHistoricalDB(),id=compAliases[leagueId]||leagueId,latest=(db.seasons||[]).slice().sort().reverse();for(const season of latest){const teams=[...new Set((db.matches||[]).filter(m=>m.competition===id&&m.season===season).flatMap(m=>[m.home,m.away]))].sort((a,b)=>a.localeCompare(b));if(teams.length)return teams;}return[...new Set((db.matches||[]).filter(m=>m.competition===id).flatMap(m=>[m.home,m.away]))].sort((a,b)=>a.localeCompare(b));}
function isTeam(m,name){const n=norm(name),h=norm(m.home),a=norm(m.away);return h===n||a===n||h.includes(n)||a.includes(n)||n.includes(h)||n.includes(a);}
function teamSide(m,name){const n=norm(name),h=norm(m.home);return h===n||h.includes(n)||n.includes(h)?'home':'away';}
function pct(values,threshold){return values.length?Math.round(values.filter(v=>v>=threshold).length/values.length*100):null;}
function avg(values){return values.length?round(values.reduce((s,v)=>s+v,0)/values.length):null;}
function summarizeRows(rows,name,limit=30){const xs=rows.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,limit);let gf=0,ga=0,points=0,shotFor=0,shotAgainst=0,sotFor=0,sotAgainst=0,shotN=0,sotN=0;const totals={goals:[],corners:[],yellow:[],red:[],fouls:[]};for(const m of xs){const side=teamSide(m,name),f=Number(side==='home'?m.homeGoals:m.awayGoals)||0,a=Number(side==='home'?m.awayGoals:m.homeGoals)||0;gf+=f;ga+=a;points+=f>a?3:f===a?1:0;totals.goals.push(f+a);const pair=(h,a)=>valid(m[h])&&valid(m[a])?m[h]+m[a]:null;for(const [k,h,aKey] of [['corners','cornersHome','cornersAway'],['yellow','yellowHome','yellowAway'],['red','redHome','redAway'],['fouls','foulsHome','foulsAway']]){const v=pair(h,aKey);if(v!=null)totals[k].push(v);}const sf=side==='home'?m.shotsHome:m.shotsAway,sa=side==='home'?m.shotsAway:m.shotsHome;if(valid(sf)&&valid(sa)){shotFor+=sf;shotAgainst+=sa;shotN++;}const stf=side==='home'?m.shotsOnTargetHome:m.shotsOnTargetAway,sta=side==='home'?m.shotsOnTargetAway:m.shotsOnTargetHome;if(valid(stf)&&valid(sta)){sotFor+=stf;sotAgainst+=sta;sotN++;}}
const n=xs.length||1;return{sample:xs.length,gf:round(gf/n),ga:round(ga/n),ppg:round(points/n),goalDiff:round((gf-ga)/n),shotsFor:shotN?round(shotFor/shotN):null,shotsAgainst:shotN?round(shotAgainst/shotN):null,sotFor:sotN?round(sotFor/sotN):null,sotAgainst:sotN?round(sotAgainst/sotN):null,form:xs.map(m=>{const s=teamSide(m,name),f=Number(s==='home'?m.homeGoals:m.awayGoals)||0,a=Number(s==='home'?m.awayGoals:m.homeGoals)||0;return f>a?'G':f===a?'E':'P';}),totals};}
function mergeMetric(a,b){return[...(a||[]),...(b||[])];}
function resultTrend(h,a){const scoreH=h.ppg*1.6+h.goalDiff*.9+((h.sotFor??0)-(h.sotAgainst??0))*.12,scoreA=a.ppg*1.6+a.goalDiff*.9+((a.sotFor??0)-(a.sotAgainst??0))*.12,diff=Math.max(-3,Math.min(3,scoreH-scoreA)),draw=Math.max(.18,.30-Math.abs(diff)*.035),remain=1-draw,share=1/(1+Math.exp(-diff)),home=Math.round(remain*share*100),away=Math.round(remain*(1-share)*100);return{home,draw:100-home-away,away,indexHome:round(scoreH),indexAway:round(scoreA)};}
export async function analyzeHistoricalTeams(homeName,awayName,{homeLeague='',awayLeague='',limit=30}={}){const db=await loadHistoricalDB(),all=db.matches||[],hl=compAliases[homeLeague]||homeLeague,al=compAliases[awayLeague]||awayLeague,homeRows=all.filter(m=>isTeam(m,homeName)&&(!hl||m.competition===hl)),awayRows=all.filter(m=>isTeam(m,awayName)&&(!al||m.competition===al)),h=summarizeRows(homeRows,homeName,limit),a=summarizeRows(awayRows,awayName,limit),h2hRows=all.filter(m=>isTeam(m,homeName)&&isTeam(m,awayName)).sort((x,y)=>String(y.date).localeCompare(String(x.date))).slice(0,limit);let hw=0,d=0,aw=0,h2hGoals=0;for(const m of h2hRows){const hs=teamSide(m,homeName),hg=Number(hs==='home'?m.homeGoals:m.awayGoals)||0,ag=Number(hs==='home'?m.awayGoals:m.homeGoals)||0;h2hGoals+=hg+ag;if(hg>ag)hw++;else if(hg===ag)d++;else aw++;}
const goals=mergeMetric(h.totals.goals,a.totals.goals),corners=mergeMetric(h.totals.corners,a.totals.corners),yellow=mergeMetric(h.totals.yellow,a.totals.yellow),red=mergeMetric(h.totals.red,a.totals.red),fouls=mergeMetric(h.totals.fouls,a.totals.fouls);return{home:h,away:a,homeName,awayName,trend:resultTrend(h,a),metrics:{goals:{sample:goals.length,average:avg(goals),onePlus:pct(goals,1),twoPlus:pct(goals,2),threePlus:pct(goals,3),fourPlus:pct(goals,4)},corners:{sample:corners.length,average:avg(corners),fivePlus:pct(corners,5),sevenPlus:pct(corners,7),ninePlus:pct(corners,9),elevenPlus:pct(corners,11)},yellow:{sample:yellow.length,average:avg(yellow),twoPlus:pct(yellow,2),fourPlus:pct(yellow,4),sixPlus:pct(yellow,6)},red:{sample:red.length,average:avg(red),onePlus:pct(red,1)},fouls:{sample:fouls.length,average:avg(fouls)}},h2h:{sample:h2hRows.length,homeWins:hw,draws:d,awayWins:aw,goals:h2hRows.length?round(h2hGoals/h2hRows.length):null},generatedAt:db.generatedAt||'',source:db.source||''};}
