import {competitions} from "../data/competitions.js";
import {esc} from "../ui/ui.js";
import {getLocalMatches,summarizeGoals,SEASONS} from "../services/local-history.js";
const SOURCE_CODES={"premier-league":"PL","championship":"ELC","bundesliga":"BL1","bundesliga-2":"BL2","laliga":"PD","ligue-1":"FL1","serie-a":"SA","primeira-liga":"PPL"};
const fmtDate=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString("es-BO",{day:"2-digit",month:"short",year:"numeric"}):"—";
export async function competitionHistoryView(id="premier-league",season="2025-26"){
 const c=competitions.find(x=>x.id===id)||competitions[0],code=SOURCE_CODES[c.id]||c.id;
 let rows=[];try{rows=await getLocalMatches({competition:code,season});}catch(e){return `<div class="empty"><strong>No se pudo abrir la base histórica local.</strong><br><span class="muted">${esc(e.message)}</span></div>`;}
 const teams=new Set();rows.forEach(r=>{teams.add(r.home);teams.add(r.away);});const stats=summarizeGoals(rows);
 return `<div class="section-title"><div><h2>${esc(c.name)} · ${esc(SEASONS.find(s=>s[0]===season)?.[1]||season)}</h2><span class="muted">Archivo local de partidos ya disputados.</span></div><span class="badge">${rows.length} partidos</span></div><div class="search-row"><select id="competitionSeason">${SEASONS.map(([v,n])=>`<option value="${v}" ${v===season?'selected':''}>${n}</option>`).join("")}</select></div><div class="grid"><article class="card"><span class="badge">Temporada</span><h3>${esc(SEASONS.find(s=>s[0]===season)?.[1]||season)}</h3><p class="muted">${rows.length} partidos · ${teams.size} equipos</p></article><article class="card"><span class="badge">Goles</span><h3>${stats?.averageGoals??"Sin datos"}</h3><p class="muted">promedio por partido</p></article><article class="card"><span class="badge">Frecuencias</span><p>1+ gol: <strong>${stats?.onePlus??"Sin datos"}%</strong></p><p>2+ goles: <strong>${stats?.twoPlus??"Sin datos"}%</strong></p><p>3+ goles: <strong>${stats?.threePlus??"Sin datos"}%</strong></p></article></div><div class="card"><div class="section-title"><div><h3>Partidos históricos</h3><span class="muted">Datos almacenados localmente.</span></div></div>${rows.length?`<div class="history-list">${rows.map(r=>`<article class="history-row"><div><small>${fmtDate(r.date)}</small><strong>${esc(r.home)}</strong></div><b>${r.homeGoals}–${r.awayGoals}</b><div><strong>${esc(r.away)}</strong><small>${r.totalGoals} goles</small></div></article>`).join("")}</div>`:`<div class="empty">No hay partidos históricos para esta temporada.</div>`}</div>`;
}
